@echo off
echo Changing directory to Vite project...
cd C:\Users\satyarth.gaur\Downloads\Inferrix_AI_Agent_Demo_Complete_Final\frontend

echo Starting Vite dev server on port 5173...
start cmd /k "npm run dev"

echo Waiting 5 seconds to ensure Vite is running...
timeout /t 5 >nul

echo Starting ngrok tunnel on port 5173...
start cmd /k "ngrok http 5173"
